sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO="django>=1.11.0,<1.12.0"
- DJANGO="django>=2.0,<2.1"
- DJANGO="django>=2.1,<2.2"
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="django>=2.0,<2.1"
  - python: '2.7'
    env: DJANGO="django>=2.1,<2.2"
  - python: '3.4'
    env: DJANGO="django>=2.1,<2.2"
before_install:
- pip install codecov
install:
- pip install $DJANGO -e .
script:
- coverage run --source=parler_rest runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: M/+por3krrxz88oO5eJtnuEosBH1aP/if9tJzEYmlTrUOUttDjywT2FRU7+7rwU8KXzFGh3R1Qk8dboGUKGMXu/YA6kgKnb0NKXuC5mCfNeQYGNgIKRhkZiBVsRwbE4b7pQE0B4uxgWtPM3urD/q8Y+rIKHf7Cj9GGcW1NrRGAc=
    on_success: never
    on_failure: always
